-- Upstream baseline with local readability adjustments; see DESIGN.md.
-- Derived from blazkowolf/gruber-darker.nvim; see LICENSE.gruber-darker.
return function(c)
  return {
    ['@boolean'] = { link = 'Boolean' },
    ['@character'] = { link = 'Character' },
    ['@character.special'] = { link = 'Constant' },
    ['@comment'] = { link = 'Comment' },
    ['@comment.documentation'] = { italic = true, link = 'GruberDarkerGreen' },
    ['@comment.luadoc'] = { link = '@comment.documentation' },
    ['@conditional'] = { fg = c['yellow'] },
    ['@conditional.ternary'] = {},
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = { link = 'GruberDarkerYellow' },
    ['@constant.macro'] = { link = 'Define' },
    ['@constructor'] = { link = 'Function' },
    ['@debug'] = { link = 'Debug' },
    ['@define'] = { link = 'Define' },
    ['@error'] = {},
    ['@field'] = { link = 'GruberDarkerNiagara' },
    ['@float'] = { link = 'Float' },
    ['@function'] = { link = 'Function' },
    ['@function.builtin'] = { link = 'GruberDarkerYellow' },
    ['@function.macro'] = { link = 'Macro' },
    ['@keyword'] = { link = 'Keyword' },
    ['@label'] = { link = 'Label' },
    ['@method'] = { link = 'Function' },
    ['@none'] = { bg = c['none'], fg = c['none'] },
    ['@number'] = { link = 'Number' },
    ['@operator'] = { link = 'Operator' },
    ['@parameter'] = { link = 'Identifier' },
    ['@preproc'] = { link = 'PreProc' },
    ['@property'] = { link = 'GruberDarkerNiagara' },
    ['@punctuation.bracket'] = { link = 'GruberDarkerWisteria' },
    ['@punctuation.delimiter'] = { link = 'Delimiter' },
    ['@punctuation.special'] = { link = 'GruberDarkerBrown' },
    ['@repeat'] = { link = 'Repeat' },
    ['@storageclass'] = { link = 'StorageClass' },
    ['@string'] = { link = 'String' },
    ['@string.documentation'] = { link = 'String' },
    ['@string.escape'] = { link = 'Constant' },
    ['@string.regex'] = { link = 'Constant' },
    ['@string.special'] = { link = 'Constant' },
    ['@tag'] = { link = 'Tag' },
    ['@tag.attribute'] = { link = '@field' },
    ['@tag.delimiter'] = { link = 'Delimiter' },
    ['@text'] = { link = 'Normal' },
    ['@text.danger'] = { link = 'ErrorMsg' },
    ['@text.diff.add'] = { link = 'DiffAdd' },
    ['@text.diff.change'] = { link = 'DiffChange' },
    ['@text.diff.delete'] = { link = 'DiffDelete' },
    ['@text.emphasis'] = { link = 'Italic' },
    ['@text.literal'] = { link = 'Constant' },
    ['@text.note'] = { link = 'Comment' },
    ['@text.reference'] = { link = 'GruberDarkerYellowBold' },
    ['@text.strike'] = { strikethrough = true },
    ['@text.strong'] = { link = 'Bold' },
    ['@text.title'] = { link = 'Title' },
    ['@text.todo'] = { link = 'Todo' },
    ['@text.underline'] = { link = 'Underlined' },
    ['@text.uri'] = { fg = c['niagara'], underline = true },
    ['@text.warning'] = { link = 'WarningMsg' },
    ['@type'] = { link = 'Type' },
    ['@type.builtin'] = { link = 'GruberDarkerYellow' },
    ['@type.definition'] = { link = 'Typedef' },
    ['@variable'] = { link = 'Identifier' },
    ['@variable.member'] = { link = '@property' },
    ['@variable.builtin'] = { link = 'GruberDarkerYellow' },
    ['Bold'] = { bold = true },
    ['Boolean'] = { link = 'GruberDarkerYellowBold' },
    ['Character'] = { fg = c['green'], italic = true },
    ['CmpItemAbbr'] = { fg = c['white'] },
    ['CmpItemAbbrDeprecated'] = {},
    ['CmpItemAbbrMatch'] = { link = 'GruberDarkerYellowBold' },
    ['CmpItemAbbrMatchFuzzy'] = { link = 'GruberDarkerBrownBold' },
    ['CmpItemKind'] = { fg = c['white'] },
    ['CmpItemKindColor'] = { fg = c['yellow'] },
    ['CmpItemKindConstant'] = { link = 'Constant' },
    ['CmpItemKindConstructor'] = { link = 'Function' },
    ['CmpItemKindEnum'] = { link = 'Type' },
    ['CmpItemKindEnumMember'] = { link = 'Type' },
    ['CmpItemKindEvent'] = { fg = c['brown'] },
    ['CmpItemKindField'] = { link = 'GruberDarkerNiagara' },
    ['CmpItemKindFile'] = { fg = c['wisteria'] },
    ['CmpItemKindFolder'] = { fg = c['wisteria'] },
    ['CmpItemKindFunction'] = { link = 'Function' },
    ['CmpItemKindInterface'] = { link = 'Type' },
    ['CmpItemKindKeyword'] = { link = 'Keyword' },
    ['CmpItemKindMethod'] = { link = 'Function' },
    ['CmpItemKindModule'] = { link = 'Define' },
    ['CmpItemKindOperator'] = { link = 'Operator' },
    ['CmpItemKindProperty'] = { link = 'GruberDarkerDarkNiagara' },
    ['CmpItemKindReference'] = { fg = c['wisteria'] },
    ['CmpItemKindSnippet'] = { link = 'GruberDarkerDarkNiagara' },
    ['CmpItemKindStruct'] = { link = 'GruberDarkerNiagara' },
    ['CmpItemKindText'] = { fg = c['fg+2'] },
    ['CmpItemKindTypeParameter'] = { link = 'Identifier' },
    ['CmpItemKindUnit'] = { link = 'GruberDarkerDarkNiagara' },
    ['CmpItemKindValue'] = { link = 'Type' },
    ['CmpItemKindVariable'] = { link = 'Identifier' },
    ['CmpItemMenu'] = { fg = c['white'] },
    ['CmpitemKindClass'] = { link = 'Type' },
    ['ColorColumn'] = { bg = c['bg+2'] },
    ['Comment'] = { fg = c['brown'], italic = true },
    ['CompileModeCheckResult'] = { link = 'GruberDarkerWisteriaBold' },
    ['CompileModeCheckTarget'] = { link = 'GruberDarkerWisteriaBold' },
    ['CompileModeCommandOutput'] = { link = 'GruberDarkerNiagara' },
    ['CompileModeDirectoryMessage'] = { link = 'GruberDarkerNiagara' },
    ['CompileModeError'] = { link = 'GruberDarkerRed' },
    ['CompileModeInfo'] = { link = 'GruberDarkerGreen' },
    ['CompileModeMessageCol'] = { link = 'GruberDarkerGreen' },
    ['CompileModeMessageRow'] = { link = 'GruberDarkerYellow' },
    ['CompileModeOutputFile'] = { link = 'GruberDarkerYellowBold' },
    ['CompileModeWarning'] = { link = 'GruberDarkerBrown' },
    ['Conceal'] = { bg = c['bg'], fg = c['fg'] },
    ['Conditional'] = { link = 'GruberDarkerYellowBold' },
    ['Constant'] = { link = 'GruberDarkerQuartz' },
    ['CurSearch'] = { link = 'IncSearch' },
    ['Cursor'] = { bg = c['yellow'] },
    ['CursorColumn'] = { bg = c['bg+2'] },
    ['CursorIM'] = { bg = c['yellow'], fg = c['none'] },
    ['CursorLine'] = { bg = c['bg+1'] },
    ['CursorLineNr'] = { fg = c['yellow'] },
    ['Debug'] = { link = 'GruberDarkerFg2' },
    ['Define'] = { link = 'GruberDarkerQuartz' },
    ['Delimiter'] = { link = 'GruberDarkerFg0' },
    ['DiagnosticError'] = { link = 'GruberDarkerRedBold' },
    ['DiagnosticHint'] = { link = 'GruberDarkerWisteria' },
    ['DiagnosticInfo'] = { link = 'GruberDarkerGreenBold' },
    ['DiagnosticSignError'] = { link = 'GruberDarkerRedSign' },
    ['DiagnosticSignHint'] = { link = 'GruberDarkerWisteriaSign' },
    ['DiagnosticSignInfo'] = { link = 'GruberDarkerGreenSign' },
    ['DiagnosticSignWarn'] = { link = 'GruberDarkerYellowSign' },
    ['DiagnosticUnderlineError'] = { link = 'GruberDarkerRedUnderline' },
    ['DiagnosticUnderlineHint'] = { link = 'GruberDarkerWisteriaUnderline' },
    ['DiagnosticUnderlineInfo'] = { link = 'GruberDarkerGreenUnderline' },
    ['DiagnosticUnderlineWarn'] = { link = 'GruberDarkerYellowUnderline' },
    ['DiagnosticUnnecessary'] = { link = 'DiagnosticUnderlineHint' },
    -- Inline messages are quieter than syntax; gutter signs retain severity colors.
    ['DiagnosticVirtualTextError'] = { fg = c['red'] },
    ['DiagnosticVirtualTextWarn'] = { fg = c['brown'] },
    ['DiagnosticVirtualTextInfo'] = { fg = c['quartz'] },
    ['DiagnosticVirtualTextHint'] = { fg = c['wisteria'] },
    ['DiagnosticWarn'] = { link = 'GruberDarkerYellowBold' },
    ['DiffAdd'] = { bg = c['bg+1'], fg = c['green'] },
    ['DiffChange'] = { bg = c['bg+1'], fg = c['yellow'] },
    ['DiffDelete'] = { bg = c['bg+1'], fg = c['red+1'] },
    ['DiffText'] = { bg = c['bg+2'], bold = true, fg = c['fg'], underline = true },
    ['Directory'] = { link = 'GruberDarkerNiagaraBold' },
    ['EndOfBuffer'] = { bg = c['none'], fg = c['bg+4'] },
    ['ErrorMsg'] = { bg = c['red'], fg = c['black'], bold = true },
    ['Exception'] = { link = 'GruberDarkerYellowBold' },
    ['Float'] = { link = 'GruberDarkerWisteria' },
    ['FloatBorder'] = { bg = c['none'], fg = c['bg+4'] },
    ['FoldColumn'] = { bg = c['bg+2'], fg = c['brown'] },
    ['Folded'] = { bg = c['bg+2'], fg = c['fg'], italic = true },
    ['Function'] = { link = 'GruberDarkerNiagara' },
    ['GitSignsAdd'] = { link = 'DiffAdd' },
    ['GitSignsChange'] = { link = 'DiffChange' },
    ['GitSignsDelete'] = { link = 'DiffDelete' },
    ['GruberDarkerBg0'] = { fg = c['bg'] },
    ['GruberDarkerBg1'] = { fg = c['bg+1'] },
    ['GruberDarkerBg2'] = { fg = c['bg+2'] },
    ['GruberDarkerBg3'] = { fg = c['bg+3'] },
    ['GruberDarkerBg4'] = { fg = c['bg+4'] },
    ['GruberDarkerBg_1'] = { fg = c['bg-1'] },
    ['GruberDarkerBrown'] = { fg = c['brown'] },
    ['GruberDarkerBrownBold'] = { bold = true, fg = c['brown'] },
    ['GruberDarkerDarkNiagara'] = { fg = c['niagara-1'] },
    ['GruberDarkerDarkNiagaraBold'] = { bold = true, fg = c['niagara-1'] },
    ['GruberDarkerDarkRed'] = { fg = c['red-1'] },
    ['GruberDarkerDarkRedBold'] = { bold = true, fg = c['red-1'] },
    ['GruberDarkerDarkestNiagara'] = { fg = c['niagara-2'] },
    ['GruberDarkerDarkestNiagaraBold'] = { bold = true, fg = c['niagara-2'] },
    ['GruberDarkerFg0'] = { fg = c['fg'] },
    ['GruberDarkerFg1'] = { fg = c['fg+1'] },
    ['GruberDarkerFg2'] = { fg = c['fg+2'] },
    ['GruberDarkerGreen'] = { fg = c['green'] },
    ['GruberDarkerGreenBold'] = { bold = true, fg = c['green'] },
    ['GruberDarkerGreenSign'] = { fg = c['green'], reverse = false },
    ['GruberDarkerGreenUnderline'] = { sp = c['green'], undercurl = true },
    ['GruberDarkerLightRed'] = { fg = c['red+1'] },
    ['GruberDarkerLightRedBold'] = { bold = true, fg = c['red+1'] },
    ['GruberDarkerNiagara'] = { fg = c['niagara'] },
    ['GruberDarkerNiagaraBold'] = { bold = true, fg = c['niagara'] },
    ['GruberDarkerNiagaraSign'] = { fg = c['niagara'], reverse = false },
    ['GruberDarkerNiagaraUnderline'] = { sp = c['niagara'], undercurl = true },
    ['GruberDarkerQuartz'] = { fg = c['quartz'] },
    ['GruberDarkerQuartzBold'] = { bold = true, fg = c['quartz'] },
    ['GruberDarkerQuartzSign'] = { fg = c['quartz'], reverse = false },
    ['GruberDarkerQuartzUnderline'] = { sp = c['quartz'], undercurl = true },
    ['GruberDarkerRed'] = { fg = c['red'] },
    ['GruberDarkerRedBold'] = { bold = true, fg = c['red'] },
    ['GruberDarkerRedSign'] = { fg = c['red'], reverse = false },
    ['GruberDarkerRedUnderline'] = { sp = c['red'], undercurl = true },
    ['GruberDarkerWisteria'] = { fg = c['wisteria'] },
    ['GruberDarkerWisteriaBold'] = { bold = true, fg = c['wisteria'] },
    ['GruberDarkerWisteriaSign'] = { fg = c['wisteria'], reverse = false },
    ['GruberDarkerWisteriaUnderline'] = { sp = c['wisteria'], undercurl = true },
    ['GruberDarkerYellow'] = { fg = c['yellow'] },
    ['GruberDarkerYellowBold'] = { bold = true, fg = c['yellow'] },
    ['GruberDarkerYellowSign'] = { fg = c['yellow'], reverse = false },
    ['GruberDarkerYellowUnderline'] = { sp = c['yellow'], undercurl = true },
    ['Identifier'] = { link = 'GruberDarkerFg1' },
    ['IncSearch'] = { bg = c['fg+2'], fg = c['black'] },
    ['Include'] = { link = 'GruberDarkerQuartz' },
    ['Italic'] = { italic = true },
    ['Keyword'] = { link = 'GruberDarkerYellowBold' },
    ['Label'] = { link = 'GruberDarkerYellowBold' },
    ['LineNr'] = { fg = c['bg+4'] },
    ['Macro'] = { link = 'GruberDarkerQuartz' },
    ['MatchParen'] = { bg = c['wisteria'], fg = c['black'], bold = true },
    ['ModeMsg'] = { link = 'GruberDarkerFg2' },
    ['MoreMsg'] = { fg = c['fg+2'] },
    ['NonText'] = { link = 'EndOfBuffer' },
    ['Normal'] = { bg = c['bg'], fg = c['fg'] },
    ['NormalFloat'] = { bg = c['bg+1'], fg = c['fg'] },
    ['NormalNC'] = { bg = c['bg'], fg = c['fg'] },
    ['NormalSB'] = { bg = c['bg-1'], fg = c['fg'] },
    ['Number'] = { link = 'GruberDarkerWisteria' },
    ['Operator'] = { fg = c['fg'], italic = false },
    ['Pmenu'] = { bg = c['bg+1'], fg = c['fg'] },
    ['PmenuSbar'] = { bg = c['bg'] },
    ['PmenuSel'] = { bg = c['bg+2'], fg = c['fg'] },
    ['PmenuThumb'] = { bg = c['bg'] },
    ['PreCondit'] = { link = 'GruberDarkerQuartz' },
    ['PreProc'] = { link = 'GruberDarkerQuartz' },
    ['Question'] = { fg = c['niagara'] },
    ['QuickFixLine'] = { bg = c['bg+2'], bold = true },
    ['RainbowDelimiterBlue'] = { fg = c['niagara'] },
    ['RainbowDelimiterCyan'] = { fg = c['quartz'] },
    ['RainbowDelimiterGreen'] = { fg = c['green'] },
    ['RainbowDelimiterOrange'] = { fg = c['brown'] },
    ['RainbowDelimiterRed'] = { fg = c['red+1'] },
    ['RainbowDelimiterViolet'] = { fg = c['wisteria'] },
    ['RainbowDelimiterYellow'] = { fg = c['yellow'] },
    ['Repeat'] = { link = 'GruberDarkerYellowBold' },
    ['SagaBorder'] = { link = 'FloatBorder' },
    ['SagaNormal'] = { link = 'NormalFloat' },
    ['Search'] = { bg = c['fg+1'], fg = c['niagara-1'] },
    ['SignColumn'] = { bg = c['none'], fg = c['bg+2'] },
    ['Special'] = { link = 'GruberDarkerYellow' },
    ['SpecialChar'] = { link = 'GruberDarkerYellow' },
    ['SpecialComment'] = { link = 'GruberDarkerWisteriaBold' },
    ['SpecialKey'] = { fg = c['fg+2'] },
    ['SpellBad'] = { link = 'GruberDarkerRedUnderline' },
    ['SpellCap'] = { undercurl = true },
    ['SpellLocal'] = { undercurl = true },
    ['SpellRare'] = { undercurl = true },
    ['Statement'] = { fg = c['yellow'] },
    ['StatusLine'] = { bg = c['bg+1'], fg = c['white'] },
    ['StatusLineNC'] = { bg = c['bg+1'], fg = c['quartz'] },
    ['StorageClass'] = { link = 'GruberDarkerYellowBold' },
    ['String'] = { fg = c['green'], italic = true },
    ['Structure'] = { link = 'GruberDarkerYellowBold' },
    ['TabLine'] = { bg = c['none'] },
    ['TabLineFill'] = { bg = c['bg+1'], fg = c['bg+4'] },
    ['TabLineSel'] = { bg = c['none'], bold = true, fg = c['yellow'] },
    ['Tag'] = { link = 'GruberDarkerYellow' },
    ['TelescopeBorder'] = { link = 'FloatBorder' },
    ['TelescopeMatching'] = { link = 'GruberDarkerYellowBold' },
    ['TelescopeMultiSelection'] = { link = 'CursorLine' },
    ['TelescopeNormal'] = {},
    ['TelescopePromptPrefix'] = { link = 'GruberDarkerNiagara' },
    ['TelescopeSelection'] = { bg = c['bg+1'], fg = c['fg+2'] },
    ['TelescopeSelectionCaret'] = { link = 'GruberDarkerYellow' },
    ['TelescopeTitle'] = { fg = c['white'] },
    ['TermCursor'] = { bg = c['yellow'] },
    ['Title'] = { link = 'GruberDarkerQuartz' },
    ['Todo'] = { bg = c['yellow'], fg = c['bg'] },
    ['Type'] = { link = 'GruberDarkerQuartz' },
    ['Typedef'] = { link = 'GruberDarkerYellowBold' },
    ['Underlined'] = { fg = c['wisteria'], underline = true },
    ['VertSplit'] = { bg = c['bg+1'], fg = c['fg+2'] },
    ['Visual'] = { bg = c['bg+2'], reverse = false },
    ['VisualNOS'] = { link = 'GruberDarkerRed' },
    ['WarningMsg'] = { link = 'GruberDarkerRed' },
    ['Whitespace'] = { bg = c['none'], fg = c['bg+4'] },
    ['WildMenu'] = { bg = c['yellow'], fg = c['black'] },
    ['WinSeparator'] = { bold = true, fg = c['bg+2'] },
    ['diffAdded'] = { link = 'DiffAdd' },
    ['diffLine'] = { link = 'DiffChange' },
    ['diffRemoved'] = { link = 'DiffDelete' },
    -- Native Vue syntax links the whole script region to Special (yellow).
    ['javaScript'] = { link = 'Identifier' },
    ['lCursor'] = { bg = c['yellow'], fg = c['none'] },
    ['markdownBold'] = { link = 'GruberDarkerYellowBold' },
    ['markdownCode'] = { fg = c['green'] },
    ['markdownCodeBlock'] = { fg = c['green'] },
    ['markdownCodeDelimiter'] = { fg = c['brown'], italic = true },
    ['markdownError'] = { bg = c['bg+1'], fg = c['fg'] },
    ['markdownHeadingDelimiter'] = { bold = true, fg = c['niagara'] },
    ['markdownItalic'] = { fg = c['wisteria'], italic = true },
  }
end
