-- Shared by language configuration, environment checks, and installation.
return {
  parsers = {
    'bash',
    'c',
    'diff',
    'json',
    'css',
    'scss',
    'html',
    'jsdoc',
    'lua',
    'luadoc',
    'markdown',
    'markdown_inline',
    'query',
    'regex',
    'typescript',
    'javascript',
    'tsx',
    'rust',
    'sql',
    'toml',
    'vue',
    'python',
    'yaml',
  },
  servers = {
    lua_ls = 'lua-language-server',
    vtsls = 'vtsls',
    vue_ls = 'vue-language-server',
    eslint = 'eslint-lsp',
    oxlint = 'oxlint',
    tailwindcss = 'tailwindcss-language-server',
    html = 'html-lsp',
    cssls = 'css-lsp',
    jsonls = 'json-lsp',
    yamlls = 'yaml-language-server',
    basedpyright = 'basedpyright',
    ruff = 'ruff',
    sqruff = 'sqruff',
  },
  tools = { 'stylua', 'prettierd', 'prettier', 'oxfmt', 'shfmt', 'markdownlint', 'debugpy', 'js-debug-adapter', 'codelldb' },
  system = {
    { name = 'git', brew = 'git' },
    { name = 'curl', brew = 'curl' },
    { name = 'tar', brew = 'gnu-tar' },
    { name = 'cc', help = '安装 C 编译器；macOS 可执行 xcode-select --install' },
    { name = 'make', brew = 'make' },
    { name = 'unzip', brew = 'unzip' },
    { name = 'rg', brew = 'ripgrep' },
    { name = 'fd', brew = 'fd' },
    { name = 'node', brew = 'node', minimum = '20.19.0' },
    { name = 'npm', brew = 'node' },
    { name = 'python3', brew = 'python' },
    { name = 'rustup', brew = 'rustup' },
    { name = 'tree-sitter', brew = 'tree-sitter-cli', minimum = '0.26.1' },
  },
}
